name: Sygn files to gh-pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
  
jobs:
  sygn-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Copy to gh-pages
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: README.md
          branches: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
